baseURL: http://paolomarchetti.my.to/blog
defaultContentLanguage: "it"
title: Paolo Marchetti
theme: 
- "nightfall_ext"
- "nightfall"
params:
  user: "Paolo"
  author:
    name: "Paolo Marchetti"
    email: "paolo.marchetti.it@gmail.com"
  social:
    - name: "github"
      url: "https://github.com/paolomarr"
      icon: "fa-brands fa-github fa-xl"
      target: "_blank"
      aria: "GitHub Profile"
    - name: "email"
      icon: "fa-solid fa-envelope fa-xl"
      url: "mailto:paolo.marchetti.it@gmail.com"
    - name: "linkedin"
      icon: "fa-brands fa-linkedin fa-xl"
      url: "https://www.linkedin.com/in/paolo-marchetti-32678a42/"
menu:
  header:
  - name: Blog
    weight: 0
    url: "/blog"    

languages:
  it:
    languageCode: "it-IT"
    weight: 1
  en:
    languageCode: "en-US"
    weight: 2

markup:
  goldmark:
    renderer:
      unsafe: true